### ISSUE TITLE
Tickets cannot be linked when the status of the ticket is "Closed"

### ISSUE THREAD

**Issue by RoofD82** [alexdglover/linkets#1]
Hey Alex,

In using the linkets app, sometimes we'll want to link current tickets to older tickets that have been closed long ago.  Currently, your application will not allow this, and also states incorrectly that the link has been added successfully when you try.

Replication steps:  Try linking tickets both of which have a status of "Closed".

**Comment by alexdglover** [comment]
Hey @RoofD82 thanks for raising the issue. I believe this is because "Closed" tickets can not be updated in any way, including tags. Hence Linkets breaks when you try to link a closed ticket, because the tags can't be created. The only solution I can offer is to exclude "Closed" tickets from the search results to avoid this issue, but I don't think it is possible to support linking of closed tickets. Let me know what you think

**Comment by RoofD82** [comment]
Another option could be to simply allow the link to a Closed ticket, but not tag the ticket, which would mean an update within the ticket properties isn't necessary.  However, I don't know if the tagging is critical to having the application work the way it does today.  Is it?

All in all, the use case is relevant as I may want to link to a current ticket where the same incident happened in the past, and I want to have that older ticket info handy in the linkets app if necessary.

**Comment by alexdglover** [comment]
Unfortunately yes, the tagging is critical to how Linkets works. That is where the relationship metadata is written. Without being able to write new tags, the tickets aren't "aware" of one another. Linking two closed tickets will never work for this reason. As you suggested, the app could be refactored to create one-way relationships in the case that one of the two tickets is closed - basically the non-closed ticket would show a link to the closed ticket, but not vice-versa. 

Should be easy enough to implement, I'll let you know as I make progress. 

For my own tracking purposes, how'd you end up on this issue board? This repo is deprecated now that Linkets is an "official" Zendesk Labs app. New issues should be logged [here](https://github.com/zendesklabs/linkets/issues)

**Comment by RoofD82** [comment]
Hey Alex, I ended up here because of the "Report bug" link within the application.  May want to update that link in the application as well.  Thanks for looking into this.

**Comment by alexdglover** [comment]
🤦‍♂️ 

Could have sworn that was updated! Thanks for catching that as well. Will let you know when I spend some time on this issue.

**Comment by alexdglover** [comment]
Hey @RoofD82 I'm going to move your issue to the official repo. Don't be alarmed that I'm closing it in this repo :)

See zendesklabs/linkets/issues/4
