### ISSUE TITLE
I can't see all my linked tickets anymore

### ISSUE THREAD

**Issue by AstridGlotin333** [alexdglover/linkets#13]
I can't see all my linked tickets anymore ...

**Comment by zenbros** [comment]
> I can't see all my linked tickets anymore ...

I'm not sure if anyone is monitoring this anymore, Astrid, but wanted to at least let you know that there is a Zendesk Option now available that does much of the same.  Linkets broke for a few of our customers several months ago and we made the switch, Globally.

https://www.zendesk.com/apps/support/linked-ticket/

**Comment by alexdglover** [comment]
Linkets is built using ticket tags, so if something happened to the tags on your tickets, Linkets would stop working as described. This isn't enough detail to debug the issue, so I'm going to close the issue as stale. Please re-open if you have more detail and would like me to take a look.
