### ISSUE TITLE
Can closed ZD tickets receive the link in question?

### ISSUE THREAD

**Issue by jruforecfut** [alexdglover/linkets#14]
I tried linking an old closed ZD ticket to an unsolved ticket.  The unsolved ticket received the link, but the closed ticket does not.  I can understand the tags on the ticket not updating on the closed ticket, but it would be nice if the older ticket retained the linkage within the app itself.

**Comment by alexdglover** [comment]
Short answer - no.

Archived tickets are not modifiable, and Linkets is built on the assumption that it can set the tags on a given ticket.
