### ISSUE TITLE
Tickets not linking after selections are made

### ISSUE THREAD

**Issue by Wonderlust124** [alexdglover/linkets#26]
**Before you submit**
- [x] I understand Zendesk does not support this app, nor does Zendesk pay for this app
- [x] I understand the author does not get paid to write or support this app, he just tries to provide a useful app
- [x] I understand that Linkets does not work on Closed tickets

**Describe the bug**
  When you link your ticket it is not showing in the linked ticket field any longer. 

**To Reproduce**
1. Go to 'linkets'
2. Click on 'search'
3. Scroll down to 'find your ticket"
4. Select a field
5. produces ticket tag
6. does add ticket link

**Expected behavior**
Once the ticket is selected as relates to or child/parent It shows the tickets that are linked in the App field.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Build [19044.2486]
 - Browser [chrome]
 - Version [Version 109.0.5414.121]

**Smartphone (please complete the following information):**
 - Browser [Chrome]

**Additional context**

![linkets error](https://user-images.githubusercontent.com/125322911/218603471-1a3d7d45-96ad-4011-ba6e-b1356ceb7976.JPG)
[Linking Tickets together- New Zen.pdf](https://github.com/alexdglover/linkets/files/10727333/Linking.Tickets.together-.New.Zen.pdf)
![linkets error](https://user-images.githubusercontent.com/125322911/218602437-6295fe8f-f686-44b5-9ba2-70994c99f479.JPG)

**Comment by skneubauer** [comment]
We are also experiencing this issue

**Comment by skneubauer** [comment]
This issue is still persisting for our team. Is there anyone that is able to help out?
