### ISSUE TITLE
Open ticket in same window

### ISSUE THREAD

**Issue by bgreeno** [alexdglover/linkets#3]
Is it possible to open a linked ticket in the same window in a Zendesk tab instead of a new tab in the browser?

**Comment by 1etoy** [comment]
Was coming here to request the same thing. 🙂

**Comment by alexdglover** [comment]
@bgreeno @1etoy great feature request, that shouldn't be a problem to implement. FWIW I agree, a new Zendesk tab is probably the better default behavior as users can always right click and select "Open in a new tab" if they prefer. I'll get this change made shortly and reply here once the new version has been pushed to the [app market place](https://www.zendesk.com/apps/)

On a different topic, please note that Linkets is now maintained in the [ZendeskLabs GitHub org](https://github.com/zendesklabs/linkets). If you have any other ideas/feature requests, please submit them there.

**Comment by alexdglover** [comment]
Hey everyone, this has been implemented and merged. See v1.0.4 here: https://github.com/zendesklabs/linkets/tree/v1.0.4

Here's the PR for anyone looking for specifics: https://github.com/zendesklabs/linkets/pull/3

If you installed Linkets from the marketplace, you'll have to wait until the app has been re-reviewed by the Zendesk app marketplace team before you can update to the latest version.

Thanks again for raising the feature request.

**Comment by bgreeno** [comment]
Alex,

You're awesome!

Best,
Ben

Ben Greeno
Head of Support Services
M: 847.630.4216
Gloo.us
