### ISSUE TITLE
Random Errors

### ISSUE THREAD

**Issue by zenbros** [alexdglover/linkets#6]
Hi Alex,

I am the CEO of ZenBros (Zendesk Partner).  

We have almost ALWAYS added Linkets for our clients.  Our client with the most volume is experiencing random errors when attempting to link tickets. We are awaiting a detailed description of the issues, but would like to know if you're willing to engage regarding them?

**Comment by alexdglover** [comment]
Hey @zenbros - sorry for the delayed response. I'm still an employee of Zendesk, and worry that this would conflict with Zendesk's professional services. Thanks for the inquiry, but I have to decline.

If you/your clients have any specific issues with the app, please feel free to report them here.
