### ISSUE TITLE
ZenDesk Column Name

### ISSUE THREAD

**Issue by aaronsnyder1** [alexdglover/linkets#7]
i am setting up additional columns in ZenDesk, and I am wondering if there is a column name that will identified whether a ticket is linked or, better, which tickets are linked to other tickets 

![linked tix](https://user-images.githubusercontent.com/29281605/80748737-0390f280-8aeb-11ea-9ab4-ca00597079d5.JPG)

**Comment by alexdglover** [comment]
Linkets uses tags to store the relationship metadata on the tickets, so tags are the only way to achieve this. Not sure if you can display tag(s) as a custom column views. Hope this helps!
